"""add
  cron job config fields

Revision ID: 3f706ddb2297
Revises: 5a1b2c3d4e5f
Create Date: 2026-01-30 07:50:04.164337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f706ddb2297'
down_revision: Union[str, None] = '5a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('env', sa.String(length=50), nullable=True),
    sa.Column('marker_expression', sa.String(length=200), nullable=True),
    sa.Column('keyword_expression', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_jobs_id'), 'cron_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_cron_jobs_project_id'), 'cron_jobs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cron_jobs_project_id'), table_name='cron_jobs')
    op.drop_index(op.f('ix_cron_jobs_id'), table_name='cron_jobs')
    op.drop_table('cron_jobs')
    # ### end Alembic commands ###
