"""add test_executions table

Revision ID: 4630cd7126cf
Revises: f77c3508a958
Create Date: 2026-01-26 16:52:28.550055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4630cd7126cf'
down_revision: Union[str, None] = 'f77c3508a958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('trigger_type', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_executions_id'), 'test_executions', ['id'], unique=False)
    op.create_index(op.f('ix_test_executions_project_id'), 'test_executions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_executions_project_id'), table_name='test_executions')
    op.drop_index(op.f('ix_test_executions_id'), table_name='test_executions')
    op.drop_table('test_executions')
    # ### end Alembic commands ###
