"""add_git_fields_and_testcase

Revision ID: f77c3508a958
Revises: 03b755f4e93d
Create Date: 2026-01-26 12:22:29.744560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77c3508a958'
down_revision: Union[str, None] = '03b755f4e93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodeid', sa.String(length=1000), nullable=False),
    sa.Column('markers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_test_cases_name'), 'test_cases', ['name'], unique=False)
    op.create_index(op.f('ix_test_cases_project_id'), 'test_cases', ['project_id'], unique=False)
    op.create_index('ix_test_cases_project_nodeid', 'test_cases', ['project_id', 'nodeid'], unique=True)
    op.add_column('projects', sa.Column('git_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('git_branch', sa.String(length=100), server_default='main', nullable=False))
    op.add_column('projects', sa.Column('last_sync_time', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('last_sync_status', sa.String(length=20), server_default='Pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_sync_status')
    op.drop_column('projects', 'last_sync_time')
    op.drop_column('projects', 'git_branch')
    op.drop_column('projects', 'git_url')
    op.drop_index('ix_test_cases_project_nodeid', table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_project_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_name'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
